### ISSUE TITLE
 iceberg_penguins.detect runtime error

### ISSUE THREAD

**Issue by bspitzbart** [iceberg-project/Penguins#13]
(base) [bspitz@login005 Penguins]$ iceberg_penguins.detect
Traceback (most recent call last):
  File "/home/bspitz/.local/bin/iceberg_penguins.detect", line 15, in <module>
    from iceberg_penguins.search.models import create_model
  File "/home/bspitz/.local/lib/python3.5/site-packages/iceberg_penguins/search/models/__init__.py", line 2, in <module>
    from models.base_model import BaseModel
ImportError: No module named 'models'

**Comment by bspitzbart** [comment]
The package installs smoothly now, but I still get the error above.  Is models not linked correctly? Is models/__init__.py correct?

**Comment by iparask** [comment]
Hello @bspitzbart, I think there are several issues along all the files of how it does imports.

The `__init__.py` you are referring is importing from `base_model`, which is in the same "path". It misses a `.` before `base_model`. Then, the base model imports from `util` which is a level up from `models`. It misses `..` before `util`. An example is [here](https://github.com/iceberg-project/Seals/blob/master/src/iceberg_seals/search/predicting/predict_sealnet.py#L21).

If you want more information you can find it [here](https://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time). Also, lets allocate half an hour in this CI meeting to discuss `imports` in python

**Comment by AymenFJA** [comment]
This problem is solved with the latest release.
