### ISSUE TITLE
Disable display visualizer.

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Penguins#14]
Remove the display check from the visualizer as HPCs do not offer displays.

**Comment by AymenFJA** [comment]
@iparask @bspitzbart  Does removing the visualizer include removing all the associated `imports`, `scripts`, etc. as well? or just the package installation from the `environment.yml` and the `README` file?

**Comment by bspitzbart** [comment]
I think you will need to comment out the imports and script calls because they will fail if the package is not installed. I say comment out instead of remove so that future users can see that the visualizer is an option.

**Comment by AymenFJA** [comment]
Great, I will work on it now. Thanks @bspitzbart

**Comment by iparask** [comment]
ping @AymenFJA

**Comment by AymenFJA** [comment]
@iparask  i need to discuss this further, during the CI meeting today.

**Comment by AymenFJA** [comment]
This ticket is solved.
