### ISSUE TITLE
Meaningful commit messages

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Penguins#2]
Hello @lmhieu612, @bspitzbart,

I was checking the state of this use case. Despite pending issue #1, it is very difficult for me to follow the development phase for the Penguins use case due to the fact that many commit messages are just a couple of letters like `cl` and `re`. Furthermore, I see no Pull requests that explain the development and or what is committed.

Do you mind if from now on this repo also follows the Development guide of the project as close as possible?

Thank you,
Giannis

**Comment by lmhieu612** [comment]
Hi @iparask,

This repo is under development. Except for the last two commit messages, which was not related to developing features (they are for cleaning and re-organizing the repo), the others are quite meaningful. 

I will make sure the repo follow the Development guide once from now on.

**Comment by bspitzbart** [comment]
We created a devel branch with the appropriate structure. Hieu will be pushing in code.

**Comment by iparask** [comment]
Thank you! Although I am not sure why it was not branched off master? I will be easier to merge after.

**Comment by bspitzbart** [comment]
Right. Fixed. It is now branched off master.

**Comment by iparask** [comment]
But everything is deleted! Is the code from master useful or not? 

I would suggest that the `devel` branch is a reorganization of the master branch. It can be done in steps. It does no need to happen in one go.

**Comment by bspitzbart** [comment]
Hieu will add the useful code from master (in a different branch, of course).  That is how we did Seals.
