### ISSUE TITLE
Files without extensions or meaningful names

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Penguins#3]
@bspitzbart @lmhieu612 folder `script` in the master branch has a lot of files with out extensions and that are not scripts. Some of the filenames also does not make any sense such as `5`, `all`, `0.25.log`.

Can we please fix that? Thank you

**Comment by bspitzbart** [comment]
The entire predicting pipeline is written in pipe.py.  We are working on separating out the kernel elements (tiling, predicting, merging) to organize in devel.

**Comment by iparask** [comment]
Pull request #4 fixes this.
